## Vector and Matrix Basics

This notebook demonstrates the following in numpy:

- how to create and reshape vectors and matrices, and
- how to operate on vectors and matrices, with broadcasting and vectorization under the hood.

Knowing these by heart allows you to correctly write deep learning code in Keras, 
TensorFlow, and Pytorch. 

In [107]:
import numpy as np

### Vector and Matrix Creation

In [108]:
# create a 1D array of 3 numbers
v = np.array([1, 2, 3])
print(v)
print(f'dimension: {v.shape}' )

[1 2 3]
dimension: (3,)


In [109]:
# create a row vector of 3 elements, i.e., a 2D array of dimension 1 x 3
v = np.array([[1, 2, 3]])
print(v)
print(f'dimension: {v.shape}' )

[[1 2 3]]
dimension: (1, 3)


In [110]:
# create a column vector of 3 elements, i.e., a 2D array of dimension 3 x 1
v = np.array([[1], [2], [3]])
print(v)
print(f'dimension: {v.shape}' )

[[1]
 [2]
 [3]]
dimension: (3, 1)


In [111]:
# create a 4x4 identity matrix 
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [112]:
# create a 1D array of 3 zeros
v = np.zeros(3)
print(v)
print(f'dimension: {v.shape}' )

[0. 0. 0.]
dimension: (3,)


In [113]:
# create a row vector of 3 zeros
v = np.zeros((1,3))
print(v)
print(f'dimension: {v.shape}' )

[[0. 0. 0.]]
dimension: (1, 3)


In [114]:
# create a col vector of 3 zeros
v = np.zeros((3, 1))
print(v)
print(f'dimension: {v.shape}' )

[[0.]
 [0.]
 [0.]]
dimension: (3, 1)


In [115]:
# create a 2x3 matrix of 6 zeros
v = np.zeros((2, 3))
print(v)
print(f'dimension: {v.shape}' )

[[0. 0. 0.]
 [0. 0. 0.]]
dimension: (2, 3)


### Vector and Matrix Reshaping

In [116]:
# create a 1D array of 6 elements
v1d = np.array([1, 2, 3, 4, 5, 6])
print(f"1d array {v1d} has dimension {v1d.shape}")

1d array [1 2 3 4 5 6] has dimension (6,)


In [117]:
# reshape to a row vector
row_vec = v1d.reshape(1, -1)
# v1d.reshape(1, -1): 
#   1 means the 1st dimension is 1 
#  -1 means the 2nd dimension is len(v1d) / 1st dimension = 6 / 1 = 6
print(f'row vector {row_vec} has dimension {row_vec.shape}')

row vector [[1 2 3 4 5 6]] has dimension (1, 6)


In [118]:
# reshape to a col vector
col_vec = v1d.reshape(-1, 1)
# v1d.reshape(-1, 1):
#   1 means the 2nd dimension is 1
#  -1 means the 1st dimension is len(v1d) / 2nd dimension = 6 / 1 = 6
print(f'column vector\n{col_vec}\nhas dimension {col_vec.shape}')

column vector
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
has dimension (6, 1)


In [119]:
# reshape to a 3 x 2 matrix
mat = v1d.reshape(3, -1)
# v1d.reshape(3, -1):
#   3 means the 1st dimension is 3
#  -1 means the 2nd dimension is len(v1d) / 1st dimension = 6 / 3 = 2
print(f"matrix\n{mat}\nhas dimension {mat.shape}")

matrix
[[1 2]
 [3 4]
 [5 6]]
has dimension (3, 2)


In [120]:
# create a matrix of zeros with the same dimension as mat
print(np.zeros_like(mat))

[[0 0]
 [0 0]
 [0 0]]


In [121]:
# find the transpose of mat
print(mat.T)

[[1 3 5]
 [2 4 6]]


### Vector and Matrix Operations

In [122]:
# 1d array + scala
# broadcasting allows addition of the scala to each vector element
v = np.array([1,2,3])
res = v + 3
print(res, f"with dimension {res.shape}")

[4 5 6] with dimension (3,)


In [123]:
# row vector + scala
v = np.array([1,2,3]).reshape(1, -1)
res = v + 3
print(res, f"with dimension {res.shape}")

[[4 5 6]] with dimension (1, 3)


In [124]:
# col vector + scala
v = np.array([1,2,3]).reshape(-1, 1)
res = v + 3
print(res, f"\nwith dimension {res.shape}")

[[4]
 [5]
 [6]] 
with dimension (3, 1)


In [125]:
# row vector + col vector = matrix 
row_vec = np.array([1,2]).reshape(1, -1)
col_vec = np.array([4,5]).reshape(-1, 1)
res = row_vec + col_vec
# 1. broadcasting expands the row and col vectors to matrices of the same dimension 
#    [[1, 2]]         [[4, 4]]
#    [[1, 2]]         [[5, 5]]
# 2. performs element-wise addition 
#   [[5, 6]]
#   [[6, 7]]
print(res, f"\nwith dimension {res.shape}")

[[5 6]
 [6 7]] 
with dimension (2, 2)


In [126]:
# dot product of 1D-arrays
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])
np.dot(v1, v2)

32

In [127]:
# dot product of row vectors, read the error message
row_v1 = np.array([[1, 2, 3]])
row_v2 = np.array([[4, 5, 6]])
np.dot(row_v1, row_v2)

ValueError: shapes (1,3) and (1,3) not aligned: 3 (dim 1) != 1 (dim 0)

In [ ]:
# dot product of row vectors, no errors
res1 = np.dot(row_v1, row_v2.T) # returns a 2D array of dimension 1x1 instead of a scala
print(res1)
res2 = np.dot(row_v2, row_v1.T) # returns a 2D array of dimension 1x1 instead of a scala
print(res2)

[[32]]
[[32]]


In [ ]:
# dot product of col vectors, read the error message
np.dot(row_v1.T, row_v2.T)

ValueError: shapes (3,1) and (3,1) not aligned: 1 (dim 1) != 3 (dim 0)

In [ ]:
# multiply a row vector by a matrix
row_vec = np.array([1, 2, 3]).reshape(1, -1) # 1 x 3
mat = np.array([[-1, 0],
                [0, 1],
                [2, 1]]) # 3 x 2
np.matmul(row_vec, mat)  # 1 x 2

array([[5, 5]])

In [ ]:
# multiply a matrix by a col vector
col_vec = np.array([5, 10, -2]).reshape(-1, 1) # 3 x 1
mat = np.array([[-1, 0, 1],
                [0, 1, -2]]) # 2 x 3
np.matmul(mat, col_vec)  # 2 x 1

array([[-7],
       [14]])

In [ ]:
# multiply a matrix by a matrix
mat1 = np.arange(10).reshape(5, 2)
print(f"matrix1:\n{mat1}\n")
mat2 = np.arange(-3, 5).reshape(2, 4)
print(f"matrix2:\n{mat2}\n")
res = np.matmul(mat1, mat2)
print(f"matrix1 x matrix2:\n{res}")

matrix1:
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]

matrix2:
[[-3 -2 -1  0]
 [ 1  2  3  4]]

matrix1 x matrix2:
[[  1   2   3   4]
 [ -3   2   7  12]
 [ -7   2  11  20]
 [-11   2  15  28]
 [-15   2  19  36]]


### Summary

This notebook demonstrates the basics of vectors and matrices in `numpy.array()`. 

### Referral

- Digital Ocean is a cloud computing platform where you can rent remote servers for cheap. 
  I have my remote data science server there. You can do the same and [get $200 credit](https://m.do.co/c/0a435cb96813). 